import { STEPS } from "@/data/roadmap";
import type { Blank } from "@/data/types";
import { EMPTY, type RoadmapState, type StepStatus } from "./store";

/**
 * A showcase is a deliberately lossy, publishable view of someone's run.
 *
 * It is safe by *construction*, not by filtering: the type has no `notes`
 * field at all, so freeform reflections can never end up in it no matter what
 * the builder UI does. Blanks are opt-in — only ones flagged `publicSafe`
 * (tool choices, headline figures) are pre-selected, and everything else has
 * to be ticked on by hand.
 */
export interface Showcase {
  /** Whose run this is — shown in the banner. */
  label: string;
  /** One-line framing shown under the banner. */
  blurb?: string;
  /** ISO date the snapshot was taken. */
  updated: string;
  steps: Record<string, StepStatus>;
  subs: Record<string, boolean>;
  /** Whitelisted blanks only. */
  blanks: Record<string, string>;
  /** stepId -> a headline sentence describing what was actually done. */
  headlines: Record<string, string>;
}

export interface Candidate {
  key: string;
  stepN: number;
  stepTitle: string;
  label: string;
  value: string;
  safe: boolean;
}

function keysFor(b: Blank): string[] {
  return b.type === "list"
    ? Array.from({ length: b.count ?? 1 }, (_, i) => `${b.id}.${i}`)
    : [b.id];
}

/** Every filled blank, tagged with whether it's pre-approved for publishing. */
export function candidates(state: RoadmapState): Candidate[] {
  const out: Candidate[] = [];
  for (const step of STEPS) {
    for (const blank of step.blanks ?? []) {
      for (const key of keysFor(blank)) {
        const value = (state.blanks[key] ?? "").trim();
        if (!value) continue;
        out.push({
          key,
          stepN: step.n,
          stepTitle: step.title,
          label: blank.label,
          value,
          // URLs are never pre-approved even if the blank were flagged safe.
          safe: !!blank.publicSafe && blank.type !== "url",
        });
      }
    }
  }
  return out;
}

export function buildShowcase(
  state: RoadmapState,
  opts: {
    label: string;
    blurb?: string;
    includeKeys: string[];
    headlines: Record<string, string>;
    today: string;
  },
): Showcase {
  const blanks: Record<string, string> = {};
  for (const key of opts.includeKeys) {
    const v = (state.blanks[key] ?? "").trim();
    if (v) blanks[key] = v;
  }

  const headlines: Record<string, string> = {};
  for (const [k, v] of Object.entries(opts.headlines)) {
    if (v.trim()) headlines[k] = v.trim();
  }

  return {
    label: opts.label,
    blurb: opts.blurb?.trim() || undefined,
    updated: opts.today,
    steps: { ...state.steps },
    subs: { ...state.subs },
    blanks,
    headlines,
  };
}

/** Turn a showcase back into app state so the UI can render it normally. */
export function showcaseToState(s: Showcase): RoadmapState {
  return {
    ...EMPTY,
    steps: s.steps ?? {},
    subs: s.subs ?? {},
    blanks: s.blanks ?? {},
    notes: {},
    daily: {},
    updatedAt: s.updated ?? "",
  };
}

export function showcaseFile(s: Showcase): string {
  return `import type { Showcase } from "@/lib/showcase";

/**
 * A published snapshot of one person's run through the roadmap, shown on the
 * live site as a worked example. Generated by the showcase builder under
 * "Your business" — it carries no notes and no unapproved fields.
 *
 * Forks: set this to \`null\` (or replace it with your own) — it is only ever
 * an example view and never becomes a visitor's starting state.
 */
export const SHOWCASE: Showcase | null = ${JSON.stringify(s, null, 2)};
`;
}
